### ISSUE TITLE
Orientation changes cause zoom to reset 

### ISSUE THREAD

**Issue by DeanWard** [huynguyencong/ImageScrollView#41]
If the user moves their device enough to make it change orientation the zoom size will reset, even when the application is locked to a particular orientation. Could this be turned off if the app is locked? If not maybe adding an option would be a good compromise?

**Comment by huynguyencong** [comment]
I don't have that issue. Can you record your screen?

**Comment by bjravalet** [comment]
I have the same issue

**Comment by huynguyencong** [comment]
I've just seen it, but sorry I won't fix it. It is intentional, not a bug.

**Comment by aaronforge** [comment]
same here.

@DeanWard @CallMeMeow 
It's because of the notification observer of `UIDevice.orientationDidChangeNotification`.
You can find the method called `private func initialize()` on the 73rd line in the file of `ImageScrollView.swift` of this library.
You can just remove the observer after you initialize the image scroll view. 
But you're gonna lose the auto rotating feature of this library.

If you don't mind, here's the solution.

```swift
private func configureView() {
        
        imageView.setup()
        contentView.addSubview(imageView)
        
        imageView.snp.makeConstraints {
            $0.edges.equalToSuperview()
        }
        
        NotificationCenter.default.removeObserver(imageView, name: UIDevice.orientationDidChangeNotification, object: nil)
}
```
